### ISSUE TITLE
wrong IP

### ISSUE THREAD

**Issue by ludobill** [mschuerig/subsonic-docker-image#6]
Hy, 

your image is great, it works well on my nas but the IP returned is the container one and not the server one make the *.subsonic.org resolution ko.

do you think it's possible to correct this ?

I've seen the --host option is available, I tried but have no succes

**Comment by mschuerig** [comment]
I'm not using subsonic.org myself so I don't know where the problem is and can't reproduce it.

In my setup, I use my DSL router to forward a port to the machine where the subsonic container is running. In particular, the forwarding is to the machine's IP, not the container's.

I don't know the intricacies of docker networking, so if you figure out a solution, please submit a pull request.

**Comment by ludobill** [comment]
No way, the --host option don't gve any result.

May be there is a solution via network configuration but I'm not very confortable with this.

**Comment by anarcat** [comment]
i think this is a docker-specific issue, not specific to this container in particular. i do believe your solution lies in network configuration. out of the box, this works fine with Docker 17. With `rkt` I had to pass `--net=host` to make it work.

Otherwise I think this issue should be closed.
